services:
  lichcongtac-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lichcongtac-backend
    expose:
      - "5000"
    ports:
      - "59607:5000"
    security_opt:
      - no-new-privileges:true
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_PATH=/app/data/documents.db
      - TZ=Asia/Ho_Chi_Minh
      - JWT_SECRET=test_secret_for_local_development_123456
      - PUBLIC_ID_SECRET=test_public_id_secret_for_local_development_123456
    volumes:
      - ./data_dump:/app/data
      - ./LichCongTac.Api/Uploads:/app/Uploads
    restart: always

  nginx:
    image: nginx:alpine
    platform: linux/amd64
    container_name: lichcongtac-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - lichcongtac-backend
    restart: always
