version: "3.3"
services:
  lichcongtac-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lichcongtac-backend
    expose:
      - "5000"
    ports:
      - "59608:5000"
    security_opt:
      - no-new-privileges:true
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - DB_PATH=${DB_PATH}
      - TZ=${TZ}
      - JWT_SECRET=${JWT_SECRET}
      - PUBLIC_ID_SECRET=${PUBLIC_ID_SECRET}
    volumes:
      - ./data_dump:/app/data

    restart: always

  nginx:
    image: nginx:alpine
    container_name: lichcongtac-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - lichcongtac-backend
    restart: always

